//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [Serializable]
    public partial class Profile
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Phone { get; set; }
    }
}
